/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as RecordImport } from "./routes/record"
import { Route as CreateImport } from "./routes/create"
import { Route as IndexImport } from "./routes/index"

// Create/Update Routes

const RecordRoute = RecordImport.update({
  id: "/record",
  path: "/record",
  getParentRoute: () => rootRoute,
} as any)

const CreateRoute = CreateImport.update({
  id: "/create",
  path: "/create",
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    "/create": {
      id: "/create"
      path: "/create"
      fullPath: "/create"
      preLoaderRoute: typeof CreateImport
      parentRoute: typeof rootRoute
    }
    "/record": {
      id: "/record"
      path: "/record"
      fullPath: "/record"
      preLoaderRoute: typeof RecordImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/create": typeof CreateRoute
  "/record": typeof RecordRoute
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/create": typeof CreateRoute
  "/record": typeof RecordRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  "/": typeof IndexRoute
  "/create": typeof CreateRoute
  "/record": typeof RecordRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/create" | "/record"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/create" | "/record"
  id: "__root__" | "/" | "/create" | "/record"
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  RecordRoute: typeof RecordRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  RecordRoute: RecordRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/create",
        "/record"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/create": {
      "filePath": "create.tsx"
    },
    "/record": {
      "filePath": "record.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
